import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./_components/session-provider";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "./_components/theme-provider";
import { AppSidebar } from '../components/app-sidebar';
import { SidebarProvider } from '@/components/ui/sidebar';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white text-black transition-colors duration-300">
        <SessionWrapper>
        {children}
        <Toaster/>
        </SessionWrapper>
      </body>
    </html>
  );
}
